name: sasa_bank
description: Sasa Bank

publish_to: 'none' 
version: 1.0.3+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.5
  url_launcher: ^6.0.20
  page_transition: ^2.0.5

flutter_native_splash:
  color: "#930c90"
  image: "assets/app/v2/imgs/splash_art.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/v3/imgs/android-logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#930c90"
  adaptive_icon_foreground: "assets/app/v3/imgs/android-logo-x05.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/v2/imgs/sasa_letters.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/app/fonts/Inter-Regular.ttf
        - asset: assets/app/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/app/fonts/Inter-SemiBold.ttf
          weight: 700